#!/usr/bin/env bash
#1. Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee file /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.facebook.com/profile.php?id=100075437905879&mibextid=ZbWKwL permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
